# Generated by Django 4.2.4 on 2024-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QPaperAnalyzerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('coursecode', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('subjectname', models.CharField(default='', max_length=200)),
                ('module1Head', models.CharField(max_length=800)),
                ('module1Syllabus', models.TextField()),
                ('module2Head', models.CharField(max_length=800)),
                ('module2Syllabus', models.TextField()),
                ('module3Head', models.CharField(max_length=800)),
                ('module3Syllabus', models.TextField()),
                ('module4Head', models.CharField(max_length=800)),
                ('module4Syllabus', models.TextField()),
                ('module5Head', models.CharField(max_length=800)),
                ('module5Syllabus', models.TextField()),
            ],
        ),
    ]
