# Generated by Django 4.2.4 on 2024-12-25 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QPaper',
            fields=[
                ('QPaper_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseCode', models.CharField(max_length=8)),
                ('Max_Marks', models.IntegerField(default=100)),
                ('Exam_Type', models.CharField(choices=[('Supply', 'Supply'), ('Regular', 'Regular')], default='Regular', max_length=7)),
                ('Exam_Name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='QPaperQuestions',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionText', models.TextField()),
                ('Mark', models.IntegerField(default=1)),
                ('Topic', models.TextField()),
                ('Module_Number', models.IntegerField(default=1)),
                ('QPaper_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QPaperAnalyzerApp.qpaper')),
            ],
        ),
    ]
