# Generated by Django 4.2.4 on 2024-12-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0004_privateqpaper_privateqpaperquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('University_ID', models.AutoField(primary_key=True, serialize=False)),
                ('University_Name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeID', models.AutoField(primary_key=True, serialize=False)),
                ('CollegeName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('University_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QPaperAnalyzerApp.university')),
            ],
        ),
    ]
