# Generated by Django 4.2.4 on 2024-12-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0005_university_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Department_Name', models.CharField(max_length=255)),
                ('College_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QPaperAnalyzerApp.college')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Course_Map',
            fields=[
                ('Dep_Cour_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QPaperAnalyzerApp.course')),
                ('Department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QPaperAnalyzerApp.department')),
            ],
        ),
    ]
