# Generated by Django 4.2.4 on 2024-12-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0006_department_department_course_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='College_ID',
        ),
        migrations.AddField(
            model_name='department',
            name='Department_Code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='CollegeDepartmentMap',
            fields=[
                ('ColDepartID', models.AutoField(primary_key=True, serialize=False)),
                ('College_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='QPaperAnalyzerApp.college')),
                ('Department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='QPaperAnalyzerApp.department')),
            ],
        ),
    ]
