# Generated by Django 4.2.4 on 2024-12-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
