# Generated by Django 4.2.4 on 2025-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0011_quizscore_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpaper',
            name='Month_Year',
            field=models.CharField(default='', max_length=200),
        ),
    ]
