# Generated by Django 4.2.4 on 2025-01-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0012_qpaper_month_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateqpaperquestions',
            name='Topic',
        ),
        migrations.RemoveField(
            model_name='qpaperquestions',
            name='Topic',
        ),
    ]
