# Generated by Django 4.2.4 on 2025-01-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0013_remove_privateqpaperquestions_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateqpaperquestions',
            name='Topic',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='qpaperquestions',
            name='Topic',
            field=models.TextField(default=''),
        ),
    ]
