# Generated by Django 4.2.4 on 2025-01-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0014_privateqpaperquestions_topic_qpaperquestions_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpaperquestions',
            name='AnswerText',
            field=models.TextField(default=''),
        ),
    ]
