# Generated by Django 4.2.4 on 2025-01-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperAnalyzerApp', '0015_qpaperquestions_answertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpaper',
            name='CourseCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QPaperAnalyzerApp.course'),
        ),
    ]
